### ISSUE TITLE
Accepted Talks need to be on their page

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#11]
Any talk with a "yes" in the first column needs to be added to the website. Dave Rolsky suggested using the Pods plugin. 

https://docs.google.com/spreadsheets/d/17yOi-bTU6M4-jZSIdSnnnxU12ck_vf_S0y1HJzomBKI/edit?usp=sharing

**Comment by autarch** [comment]
Actually, I realized we already have a plugin specialized for handling conference schedules, so we should just use that.

**Comment by autarch** [comment]
Done for now, but it can use a lot of improvement. However, to do that I need to edit the theme directly, which requires shell access.
