### ISSUE TITLE
Add Confirmed Sponsors

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#13]
craigslist - Platinum level
Grant Street Group - Bronze level
Booking.com - Diamond level
cPanel - Platinum

**Comment by SparkeyG** [comment]
I added the sponsors rough info, but I still would like to have sponsor provided graphics and slugs.

**Comment by toddr** [comment]
@SparkeyG added where?

**Comment by SparkeyG** [comment]
There is a sponsors plugin that I've added these to.

**Comment by IrishPebbles** [comment]
cPanel has also confirmed at the Platinum Level

**Comment by SparkeyG** [comment]
I need the levels for bluehost and assurant. I also need the graphics

**Comment by IrishPebbles** [comment]
Assurant is a Bronze level sponsor

**Comment by SparkeyG** [comment]
Okay, I've added the graphics and the levels. I will work on the placement of the sponsor widget

**Comment by SparkeyG** [comment]
Confirmed Sponsors are entered
