### ISSUE TITLE
Add "How to Get Around" tab under Location

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#14]
Insert this map with a bit of text:

"The TRAX Green Line runs every 15 minutes from Airport Station to Courthouse Station. This means getting to the conference hotel from the airport couldn't be easier!" 

https://www.rideuta.com/-/media/RideUTA/Maps/UTA_RAIL_Map.ashx

**Comment by SparkeyG** [comment]
Done
