### ISSUE TITLE
Error in URL

### ISSUE THREAD

**Issue by legrady** [perlconference/tpc-2018-slc#15]
I was looking at the page for MIchael Conrad's talk, and tried the link to his website. Unfortunately the URL lacks the 'http://' prefix, so the browser tries to connect to a page beneath perlconference.us, rather than a remote site. The HTML has ... 

<a href="www.nrdvana.net">www.nrdvana.net</a>

which should be

<a href="http://www.nrdvana.net">www.nrdvana.net</a>

This might be a one-off error, or it may be general.

Tom

**Comment by SparkeyG** [comment]
This one has been corrected
