### ISSUE TITLE
Add confirmed tutorials.

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2018-slc#16]
We need to have a section on the website (separate from the talk sessions) for paid tutorials.

Sections should include:

- Title
- Date of the course
- Length of course  (half day or full day)
- Maximum class size
- Speaker
- Cost  (note:  do NOT get the costs from the spreadsheet!!!)
- Link to purchase tickets
- Abstract
- Audience
- Course Outline
- Prerequisites

Data is available here:  https://docs.google.com/spreadsheets/d/1UiU1lKwar4QV-TNci9gmbWlNGA4K4P54tiwG0ohSmSc/edit#gid=1898014012

**Comment by autarch** [comment]
This is partially done. I don't see the dates in spreadsheet, and if the cost doesn't come from the spreadsheet, where does it come from?

**Comment by autarch** [comment]
I'd also note that it's not clear whether outlines should be included. I don't want it on my tutorial pages.

**Comment by autarch** [comment]
We should just ask the tutorial presenters what they want. I found all the fields on the original google doc a little confusing and it wasn't clear what each field was going to be used for. I suspect others might have the same issue.

**Comment by dwright** [comment]
@autarch Grab the dates and prices from Eventbrite.
https://www.eventbrite.com/e/the-perl-conference-in-salt-lake-city-2018-tickets-41850611305?aff=es2

The intended purpose of the outline is to give prospective attendees more detailed insight as to what will be covered in the class.    If you don't want it on yours, that's fine.

**Comment by autarch** [comment]
I think all the info is there for all the confirmed tutorials.

**Comment by dwright** [comment]
rPerl white belt should be on Sunday, not Tuesday.

https://perlconference.us/tpc-2018-slc/session/rperl-white-belt-aka-from-zero-to-rperl/

**Comment by autarch** [comment]
Oops! Fixed.
