### ISSUE TITLE
Sessions drop down needs a main conference presentations breakout

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#17]
When you hover over sessions sub menus pop up for Tutorials and Lightning talks. If you click on Sessions you get a list that contains information on both the main conference presentations AND the tutorials. There is no place that has information JUST on the main conference presentations. Please add an additional page into the Sessions drop down that is only Presentations.

Thanks!

**Comment by autarch** [comment]
I don't think we need _another_ page. I could remove the tutorials from the "Sessions" page easily enough and just put a link to the tutorials at the top of that page.

**Comment by IrishPebbles** [comment]
Whatever seems to make the most sense for you and has each of the 3 categories with its own "home".

**Comment by autarch** [comment]
I think the new design makes it quite clear that the top-level link is clickable. I changed the "Sessions" page to *not* include tutorials.
