### ISSUE TITLE
Added a Keynote Speaker page

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#18]
I added a keynote speaker page and added that to the menu. I'm posting the permalink as https://perlconference.us/tpc-2018-slc/keynote/ to the TPF blog, etc, so that would need to remain the same (or have a redirect). Please check I did everything correctly and feel free to move/fix anything I did not.

**Comment by autarch** [comment]
It seems fine for now. We'll probably move/update it as more keynotes are added.
