### ISSUE TITLE
SOC still references last year's event.

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2018-slc#19]
https://perlconference.us/tpc-2018-slc/standards-of-conduct/

"If you are subject to unacceptable behavior, notice that someone else is being subject to unacceptable behavior, or have any other concerns, please notify tpc-2017-dc-soc@googlegroups.com as soon as possible."

**Comment by autarch** [comment]
What address should we use for this year? And maybe it could just be a permanent one, like soc@perlconference.us or something?

**Comment by dwright** [comment]
@autarch  Yes, please use that.

**Comment by autarch** [comment]
Done.
