### ISSUE TITLE
Dancer Tutorial needs to have Mickey added as presenter

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#21]
https://perlconference.us/tpc-2018-slc/session/programming-the-web-with-dancer/

According to the submission both Sawyer and Mickey are teaching this. We need to adjust the page to reflect that.

https://docs.google.com/spreadsheets/d/1UiU1lKwar4QV-TNci9gmbWlNGA4K4P54tiwG0ohSmSc/edit#gid=1898014012

**Comment by autarch** [comment]
I can put Mickey's name in the body, but unfortunately there's no way to have multiple presenters associated with a session right now. This might be possible to implement, but I'm not sure how hard it would be. It's also not worth it for exactly one session.

**Comment by IrishPebbles** [comment]
Maybe change the title to "Programming the Web with Dancer, with Mickey Nasriachi" and leave Sawyer as the assigned speaker. Booking is sponsoring it, and Sawyer has made a point out of the fact we haven't included Mickey. Which reminds me, we also need to add a line about it being sponsored by Booking.

**Comment by SparkeyG** [comment]
This is done. I went w/ Lena's suggestion
