### ISSUE TITLE
Add Subscribe to Announce list to main pages

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#22]
I'm looking around the website and I don't see the subscribe to the announce list address anywhere. Can we get that up as like a footer on all the main pages?

announce@perlconference.us

**Comment by SparkeyG** [comment]
I cannot find instructions to subscribe to this list. I checked the newsletter, it also lacked instructions.

**Comment by SparkeyG** [comment]
The link http://perlconference.us/mailman/listinfo/announce_perlconference.us is now in the footer.
