### ISSUE TITLE
Sponsors page.

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2018-slc#26]
We need to have a page on the site just for the sponsors.

Any sponsor that is gold or higher is entitled to "Name, Logo, and Company Bio" on the site.

**Comment by SparkeyG** [comment]
@dwright How does https://perlconference.us/tpc-2018-slc/sponsors/ look to you?

**Comment by dwright** [comment]
@SparkeyG  Looks really good.    But, please put Diamond above Platinum.

**Comment by SparkeyG** [comment]
Fixed
