### ISSUE TITLE
Sponsor logos on home page.

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2018-slc#27]
All sponsors that are platinum or diamond level are entitled to have their logo displayed on the home page.    We need to either list those statically, or do a jumbotron or other method such that all the top sponsors are displayed without requiring a page refresh.

**Comment by SparkeyG** [comment]
1) Is there a specific location on the home page required?
2) Is this just logo's w/ links to bios?

**Comment by SparkeyG** [comment]
For a test, I removed the sponsor sidebar from the home page and added the sponsors half way down
https://perlconference.us/tpc-2018-slc/?preview_id=2&preview_nonce=a23d1934a7&_thumbnail_id=-1&preview=true

**Comment by SparkeyG** [comment]
Done
