### ISSUE TITLE
Genehack's talk link is broken.

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2018-slc#28]
https://perlconference.us/tpc-2018-slc/sessions/#368

Links to:

https://perlconference.us/tpc-2018-slc/session/introduction-to-git-for-non-developers/

Which gives a 404 error.

**Comment by autarch** [comment]
Actually, _all_ the session links are broken for some reason. I'm looking into it.

**Comment by autarch** [comment]
Ugh, this is a long time bug with WordPress & Pods. If you create custom pods content types that have individual URLs, these can break when upgrading some plugins. The fix, for the record, is to go to "Settings -> Permalink" and just hit "Save" without changing anything. Very annoying :(

**Comment by autarch** [comment]
Heh, no apology needed. I think I've done this once or twice (or ten thousand times).

**Comment by autarch** [comment]
Oops, didn't mean to close this.
