### ISSUE TITLE
Infinity Interactive needs to be addded as a Sponsor

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#29]
II is creating our app, and as part of that agreement they receive a sponsorship acknowledgement.

**Comment by SparkeyG** [comment]
At what level? Have they provided a info paragraph and an image?

**Comment by IrishPebbles** [comment]
We solve problems with technology.

We’re not your typical dev shop; not your typical IT consulting firm. We’ve been here since 1998—before the “dot-com” boom (the first one) and long enough to maybe even have a little grey in our hair. You can’t come to our office, because we don’t have an office. Our distributed team of proud polyglots live and breathe solving problems through the creative, focused application of technology.

We can’t wait to take on the most formidable problems facing your business.

![infinityinteractive_logo_250x250](https://user-images.githubusercontent.com/2327162/40375428-8d5bef30-5db9-11e8-8875-87dc5aa2e7c9.png)

**Comment by SparkeyG** [comment]
Done
