### ISSUE TITLE
Contact info missing

### ISSUE THREAD

**Issue by toddr** [perlconference/tpc-2018-slc#31]
@genehack and @jkeenan have raised an issue on IRC that there is no clear way to contact conference admins. 

<kid51>	toddr:  Is that on the website somewhere?  I couldn't locate it.  (But I think it was rjbs who really wanted to know.)
<genehack>	toddr: seconding kid51 that adding a 'contact' element to the menubar on https://perlconference.us/tpc-2018-slc/ would be a capital idea

**Comment by autarch** [comment]
What are the contact details?

**Comment by toddr** [comment]
Rather than posting an email, maybe we could do something like this? 
https://pack1655.us/contact-us/

which is using Contact Form 7 - https://wordpress.org/plugins/contact-form-7/

**Comment by autarch** [comment]
Yeah, implementing that is pretty trivial, but that form sends email somewhere. That said, I think a direct email is preferable to a web form.

**Comment by IrishPebbles** [comment]
Email us at: admin@PerlConference.us
Follow us on Twitter: @PerlConferences
Like us on Facebook: The Perl Foundation (@tpf.perl)
Subscribe to the mailing list: announce@perlconference.us

**Comment by toddr** [comment]
My thought is to minimize the spam for that email.

**Comment by toddr** [comment]
done. https://perlconference.us/tpc-2018-slc/contact
