### ISSUE TITLE
Can we get a cross link to registration from tutorial pages?

### ISSUE THREAD

**Issue by toddr** [perlconference/tpc-2018-slc#33]
https://twitter.com/spazm/status/1002597326043557888

Replying to @PerlConferences
Can we get a cross link to registration from tutorial pages?

**Comment by autarch** [comment]
Every tutorial page (and the main listing of tutorials) has always had this snippet:

```
Tutorials require an additional ticket purchase. Please <a href="https://www.eventbrite.com/e/the-perl-conference-in-salt-lake-city-2018-tickets-41850611305">purchase your ticket at Eventbrite</a>.
```
