### ISSUE TITLE
Add II App links to Website

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#34]
I'm not sure the best place to put it, but maybe the home page and the schedule page? There's no "home" link in the menu, so I think it should be on one of the pages linked in the menu. Or it can have its own page.

You've secured your ticket and travel for The Perl Conference, right? The next step is to get the TPC 2018 app by Infinity Interactive! Stay current with the #TPCiSLC scheduled talks, events, twitter feed, and more. 

Apple: https://itunes.apple.com/us/app/tpc-2018/id1384579044?mt=8 
Google:  https://play.google.com/store/apps/details?id=com.iinteractive.conferences.tpc2018&hl=en_US

**Comment by autarch** [comment]
Done. It's on the front page and in the sidebar on every other page except the schedule.
