### ISSUE TITLE
Remove cancelled Tutorials

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#35]
Please remove the pages and links for:

RPerl In Windows - Will ‘the Chill’ Braswell
RPerl Orange Belt - Will ‘the Chill’ Braswell
RPerl White Belt (AKA From Zero To RPerl) - Will ‘the Chill’ Braswell
RPerl Yellow Belt - Will ‘the Chill’ Braswell
Wheaton’s Law 101 - Mark Prather

**Comment by autarch** [comment]
Done.
