### ISSUE TITLE
Add Perl 6 as an event sponsor

### ISSUE THREAD

**Issue by IrishPebbles** [perlconference/tpc-2018-slc#36]
From Wendy: 

Yes please.  Not under our own name (WenZPerl BV), but with the name Perl 6 Community (with a link to http://www.perl6.org/ ).  With the logo of Camelia, the butterfly (see https://commons.wikimedia.org/wiki/File:Camelia.svg ).

Please have a look at how the Netherlands Perl Workshop has done this, at our request:
http://test.mongueurs.net/nlpw2018/sponsors.html

**Comment by SparkeyG** [comment]
Done
