### ISSUE TITLE
Move lightning talks wiki page into WP. Give rgeoffrey access

### ISSUE THREAD

**Issue by toddr** [perlconference/tpc-2018-slc#4]
Lightning talks are here, presumably to mimic 2017. Any reason it shouldn't be in the main site?

https://github.com/perlconference/tpc-2018-slc/wiki/Lightning-Talks

**Comment by SparkeyG** [comment]
The page has been copied and is on the WP page now. I can put a link to the wiki to list the talks?

**Comment by toddr** [comment]
That's probably the only thing he needs the wiki for.
