### ISSUE TITLE
Remove Proudly powered by WordPress from main page

### ISSUE THREAD

**Issue by toddr** [perlconference/tpc-2018-slc#5]
It's VERY prominent on the mobile view

**Comment by toddr** [comment]
AFAIK, this template is a subclass so it should be an easy fix.

**Comment by toddr** [comment]
I've subclassed template-parts/footer/site-info.php so I think I've done it right.

**Comment by toddr** [comment]
The message is gone. Need confirmation from @GeekRuthie I didn't mess something up.

**Comment by GeekRuthie** [comment]
Looks good!
